### ISSUE TITLE
Wikipedia labels

### ISSUE THREAD

**Issue by fanchyna** [shangjingbo1226/SegPhrase#9]
How did you select Wikipedia entity names in wiki_labels_quality out of all Wikipedia entity names in wiki_labels_all? In other words, what do you mean by "high quality" described in your README file? I do see relevant discussion in your paper. Or do I miss anything? Thanks!

**Comment by remenberl** [comment]
The wikipedia entity is an add-on feature in this repository. First of all,
wikipedia entity names refer to wiki article anchor texts. But not all
names are good enough to be positive labels. We used a heuristic to decide
name quality, that is, the ratio of entity surface names linked to the
entity article. Our intuition is that a high quality entity name should be
unambiguous. In other words, when users are mentioning "support vector
machine", these three words probably have anchors to the svm wiki page. But
for mentions like "a classifier", although it is mentioned frequently,  it
is not likely to be always linked to svm page.

The phrase quality here is more related to Informativeness defined in the
paper simply because the other three criteria is more all less satisfied
when we consider wiki article anchor texts.

A phrase is informative if it is indicative of a specific topic. ‘This

> paper’ is a popular and concordant phrase, but not informative in research
> publication corpus
